    {{ HTML::style('/assets/dist/support/css/jquery-ui-1.10.4.custom.min.css') }}
    {{ HTML::style('/assets/dist/support/css/font-awesome.min.css') }}
    {{ HTML::style('/assets/dist/support/css/simple-line-icons.css') }}
    {{ HTML::style('/assets/dist/support/css/bootstrap.min.css') }}
    {{ HTML::style('/assets/dist/support/css/animate.css') }}
    {{ HTML::style('/assets/dist/support/css/main.css') }}
    {{ HTML::style('/assets/dist/support/css/style-responsive.css') }}
    {{ HTML::style('/assets/dist/support/css/zabuto_calendar.min.css') }}
    {{ HTML::style('/assets/dist/support/css/pace.css') }}
    {{ HTML::style('/assets/dist/support/css/jquery.news-ticker.css') }}
