    {{ HTML::style('/assets/dist/user/css/bootstrap.min.css') }}
    {{ HTML::style('/assets/dist/user/css/bootstrap-reset.css') }}
    {{ HTML::style('/assets/dist/user/css/font-awesome.css') }}
    {{ HTML::style('/assets/dist/user/css/jquery.easy-pie-chart.css') }}
    {{ HTML::style('/assets/dist/user/css/slidebars.css') }}
    {{ HTML::style('/assets/dist/user/css/owl.carousel.css') }}
    {{ HTML::style('/assets/dist/user/css/style-responsive.css') }}
    {{ HTML::style('/assets/dist/user/css/datepicker.min.css') }}
    {{ HTML::style('/assets/dist/user/css/style.css') }}
    {{ HTML::style('/assets/dist/user/css/bootstrap-fileupload.css') }}
    {{ HTML::style('/assets/dist/user/css/bootstrap-wysihtml5.css') }}
    {{ HTML::style('/assets/dist/user/css/datepicker.css') }}
    {{ HTML::style('/assets/dist/user/css/timepicker.css') }}
    {{ HTML::style('/assets/dist/user/css/colorpicker.css') }}
    {{ HTML::style('/assets/dist/user/css/daterangepicker-bs3.css') }}
    {{ HTML::style('/assets/dist/user/css/multi-select.css') }}


    <!-- fonts -->

    {{ HTML::script('/assets/dist/user/js/jquery.js') }}
    {{ HTML::script('/assets/dist/user/js/bootstrap.min.js') }}
    {{ HTML::script('/assets/dist/user/js/jquery.validate.min.js') }}
    {{ HTML::script('/assets/dist/user/js/jquery.dcjqaccordion.2.7.js') }}
    {{ HTML::script('/assets/dist/user/js/jquery.scrollTo.min.js') }}
    {{ HTML::script('/assets/dist/user/js/jquery.nicescroll.js') }}
    {{ HTML::script('/assets/dist/user/js/jquery.sparkline.js') }}
    {{ HTML::script('/assets/dist/user/js/jquery.easy-pie-chart.js') }}
    {{ HTML::script('/assets/dist/user/js/owl.carousel.js') }}
    {{ HTML::script('/assets/dist/user/js/jquery.customSelect.min.js') }}
    {{ HTML::script('/assets/dist/user/js/respond.min.js') }}
    {{ HTML::script('/assets/dist/user/js/slidebars.min.js') }}
    {{ HTML::script('/assets/dist/user/js/sparkline-chart.js') }}
    {{ HTML::script('/assets/dist/user/js/easy-pie-chart.js') }} 
    {{ HTML::script('/assets/dist/user/js/count.js') }}
    {{ HTML::script('/assets/dist/user/js/oodoo.js') }}
    {{ HTML::script('/assets/dist/user/js/bootstrap-datepicker.min.js') }}
    {{ HTML::script('/assets/dist/user/js/bootstrap-fileupload.js') }}
    {{ HTML::script('/assets/dist/user/js/bootstrap-datepicker.js') }}
    {{ HTML::script('/assets/dist/user/js/bootstrap-datetimepicker.js') }}
    {{ HTML::script('/assets/dist/user/js/moment.min.js') }}
    {{ HTML::script('/assets/dist/user/js/daterangepicker.js') }}
    {{ HTML::script('/assets/dist/user/js/bootstrap-colorpicker.js') }}
    {{ HTML::script('/assets/dist/user/js/bootstrap-timepicker.js') }}
    {{ HTML::script('/assets/dist/user/js/jquery.multi-select.js') }}
    {{ HTML::script('/assets/dist/user/js/jquery.quicksearch.js') }}
    {{ HTML::script('/assets/dist/user/js/spinner.min.js') }}
    {{ HTML::script('/assets/dist/user/js/advanced-form-components.js') }}
    {{ HTML::script('/assets/dist/user/js/wysihtml5-0.3.0.js') }}
    {{ HTML::script('/assets/dist/user/js/bootstrap-wysihtml5.js') }}

